### ISSUE TITLE
Hard-coded use of "gold"

### ISSUE THREAD

**Issue by peti** [serokell/importify#88]
Is there any particular reason why the Cabal file hard-codes flags like `-optl-fuse-ld=gold`? I am wondering, because these choices break the build on some platforms like openSUSE Linux etc.

**Comment by ChShersh** [comment]
Hi, @peti! Thanks for your interest in _Importify_! This was done to increase linking performance of application according to this suggestions: 

https://stackoverflow.com/questions/43243322/how-to-link-with-the-gnu-gold-linker-instead-of-ld-in-haskell

But I agree with you that ability to build this on multiple machines is more important then building time and this option should be opt-in instead of opt-out. This is fixed in PR #89.
